name: Generate AQI Files

on:
  schedule:
    # This will run the action every 5 minutes
    - cron: '*/15 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering via GitHub UI (optional)

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the script to generate the files (for charts)
      - name: Generate chart files
        run: |
          python xlsx_file_generator.py  # Update with the correct script path

      # Run the script to generate the files (for province maps)
      - name: Generate map files
        run: |
          python province_map.py  # Update with the correct script path

      # Run the script to generate the files (for all station maps)
      - name: Generate map files
        run: |
          python all_stations_map.py  # Update with the correct script path

      # Commit the generated files back to the repository
      - name: Commit generated files
        run: |
          git config --global user.name "DulangaDasanayake"
          git config --global user.email "dulanganiroshan721@gmail.com"
          git add charts/* maps/*
          git diff --cached --quiet || git commit -m "Add newly generated charts and maps"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
