name: Generate AQI Files

on:
  schedule:
    # This will run the action every 15 minutes
    - cron: "*/5 * * * *" # Runs every 15 minutes
  workflow_dispatch: # Allows manual triggering via GitHub UI (optional)

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run app.py which will handle everything
      # This will execute the Flask app and generate the necessary files
      - name: Run app.py to generate files
        run: |
          python app.py

      # Commit the generated files back to the repository
      - name: Commit generated files
        run: |
          git config --global user.name "DulangaDasanayake"
          git config --global user.email "dulanganiroshan721@gmail.com"
          git add charts/* all_stations_maps/* province_maps/*
          if ! git diff --cached --quiet; then
           git commit -m "Generated chart and maps"
           git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          else
           echo "No changes to commit"
          fi
